import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from 'next-auth';
import SessionProvide from '../components/SessionProvide';
import NavMenu from '@/components/NavMenu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang='en'>
      <body className={inter.className}>
        <SessionProvide session={session}>
          <main className='mx-auto flex max-w-5xl gap-2 text-2xl'>
            <NavMenu />
            {children}
          </main>
        </SessionProvide>
      </body>
    </html>
  );
}
